services:
  hai-tpcgcamscript:
    build: .
    container_name: hai-tpcg-cam-script
    restart: unless-stopped
    ports:
      - "8067:8080"
      - "21:21"
      - "22:22"
      - "30000-30010:30000-30010"
    environment:
      TZ: ${TZ:-Europe/Berlin}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      API_KEY: ${API_KEY}
      DATA_ROOT: /data
    volumes:
      - /opt/hai-tpcg-cam-script/data:/data
    networks:
      - highfishNetwork

networks:
  highfishNetwork:
    external: true
    name: highfishNetwork
